/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bilar;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Mi pc
 */
public class DosJugadores extends javax.swing.JFrame {

    ImageIcon ima;
    Icon icono;
    
    Fondo f=new Fondo();
    
    public DosJugadores() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnPrincipal = new Fondo();
        PnJugador1 = new javax.swing.JPanel();
        BtnMas50 = new javax.swing.JButton();
        BtnMenos10 = new javax.swing.JButton();
        BtnMas20 = new javax.swing.JButton();
        lblJugador1 = new javax.swing.JLabel();
        BtnPrincipal1 = new javax.swing.JButton();
        PnJugador2 = new javax.swing.JPanel();
        BtnMas51 = new javax.swing.JButton();
        BtnMenos11 = new javax.swing.JButton();
        BtnMas21 = new javax.swing.JButton();
        lblJugador3 = new javax.swing.JLabel();
        BtnPrincipal3 = new javax.swing.JButton();
        Pnconsumo = new javax.swing.JPanel();
        lblConsumo = new javax.swing.JLabel();
        lbl$1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        PnTiempo = new javax.swing.JPanel();
        lblTiempo = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lbl$ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnJugador1.setOpaque(false);

        BtnMas50.setBackground(new java.awt.Color(255, 255, 255));
        BtnMas50.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMas50.setText("+5");

        BtnMenos10.setBackground(new java.awt.Color(255, 255, 255));
        BtnMenos10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMenos10.setText("-1");

        BtnMas20.setBackground(new java.awt.Color(255, 255, 255));
        BtnMas20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMas20.setText("+2");

        lblJugador1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador1.setText("Jugador 1");

        BtnPrincipal1.setBackground(new java.awt.Color(255, 255, 255));
        BtnPrincipal1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BtnPrincipal1.setText("0");
        BtnPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrincipal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnJugador1Layout = new javax.swing.GroupLayout(PnJugador1);
        PnJugador1.setLayout(PnJugador1Layout);
        PnJugador1Layout.setHorizontalGroup(
            PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnJugador1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblJugador1)
                        .addComponent(BtnPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PnJugador1Layout.createSequentialGroup()
                            .addComponent(BtnMas20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BtnMas50, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BtnMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        PnJugador1Layout.setVerticalGroup(
            PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnJugador1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblJugador1)
                    .addGap(2, 2, 2)
                    .addComponent(BtnPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(PnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnMas20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMas50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 40, Short.MAX_VALUE)))
        );

        PnJugador2.setOpaque(false);

        BtnMas51.setBackground(new java.awt.Color(255, 255, 51));
        BtnMas51.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMas51.setText("+5");

        BtnMenos11.setBackground(new java.awt.Color(255, 255, 51));
        BtnMenos11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMenos11.setText("-1");

        BtnMas21.setBackground(new java.awt.Color(255, 255, 51));
        BtnMas21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnMas21.setText("+2");

        lblJugador3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJugador3.setForeground(new java.awt.Color(255, 255, 51));
        lblJugador3.setText("Jugador 2");

        BtnPrincipal3.setBackground(new java.awt.Color(255, 255, 51));
        BtnPrincipal3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BtnPrincipal3.setText("0");
        BtnPrincipal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrincipal3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnJugador2Layout = new javax.swing.GroupLayout(PnJugador2);
        PnJugador2.setLayout(PnJugador2Layout);
        PnJugador2Layout.setHorizontalGroup(
            PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
            .addGroup(PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnJugador2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblJugador3)
                        .addComponent(BtnPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PnJugador2Layout.createSequentialGroup()
                            .addComponent(BtnMas21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BtnMas51, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BtnMenos11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        PnJugador2Layout.setVerticalGroup(
            PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnJugador2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblJugador3)
                    .addGap(2, 2, 2)
                    .addComponent(BtnPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(PnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnMas21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMas51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMenos11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 40, Short.MAX_VALUE)))
        );

        Pnconsumo.setBackground(new java.awt.Color(0, 255, 0));

        lblConsumo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblConsumo.setText("Consumo:");

        lbl$1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl$1.setText("$");

        lblPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio1.setText("0");

        javax.swing.GroupLayout PnconsumoLayout = new javax.swing.GroupLayout(Pnconsumo);
        Pnconsumo.setLayout(PnconsumoLayout);
        PnconsumoLayout.setHorizontalGroup(
            PnconsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnconsumoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnconsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnconsumoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl$1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecio1))
                    .addComponent(lblConsumo))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PnconsumoLayout.setVerticalGroup(
            PnconsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnconsumoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnconsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl$1)
                    .addComponent(lblPrecio1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PnTiempo.setOpaque(false);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempo.setText("Tiempo");

        lblValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor:");

        lblTimer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText("00:00");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("0");

        lbl$.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl$.setForeground(new java.awt.Color(255, 255, 255));
        lbl$.setText("$");

        javax.swing.GroupLayout PnTiempoLayout = new javax.swing.GroupLayout(PnTiempo);
        PnTiempo.setLayout(PnTiempoLayout);
        PnTiempoLayout.setHorizontalGroup(
            PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTiempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTiempo)
                    .addComponent(lblValor))
                .addGap(18, 18, 18)
                .addGroup(PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimer)
                    .addGroup(PnTiempoLayout.createSequentialGroup()
                        .addComponent(lbl$)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnTiempoLayout.setVerticalGroup(
            PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTiempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempo)
                    .addComponent(lblTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(lblPrecio)
                    .addComponent(lbl$))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnPrincipalLayout = new javax.swing.GroupLayout(PnPrincipal);
        PnPrincipal.setLayout(PnPrincipalLayout);
        PnPrincipalLayout.setHorizontalGroup(
            PnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPrincipalLayout.createSequentialGroup()
                .addComponent(PnJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Pnconsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnPrincipalLayout.setVerticalGroup(
            PnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pnconsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrincipal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrincipal1ActionPerformed

    private void BtnPrincipal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrincipal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrincipal3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosJugadores().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMas20;
    private javax.swing.JButton BtnMas21;
    private javax.swing.JButton BtnMas50;
    private javax.swing.JButton BtnMas51;
    private javax.swing.JButton BtnMenos10;
    private javax.swing.JButton BtnMenos11;
    private javax.swing.JButton BtnPrincipal1;
    private javax.swing.JButton BtnPrincipal3;
    private javax.swing.JPanel PnJugador1;
    private javax.swing.JPanel PnJugador2;
    private javax.swing.JPanel PnPrincipal;
    private javax.swing.JPanel PnTiempo;
    private javax.swing.JPanel Pnconsumo;
    private javax.swing.JLabel lbl$;
    private javax.swing.JLabel lbl$1;
    private javax.swing.JLabel lblConsumo;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}

class Fondo extends JPanel{
    private Image imagen;
    
    @Override
    public void paint(Graphics g){
    imagen = new ImageIcon(getClass().getResource("pool.jpg")).getImage();
    
    g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
    
        setOpaque(false);
        super.paint(g);
}
}